apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
discovery:
  bootstrapToken:
    apiServerEndpoint: ${MASTER_IP}:6443
    token: ${KUBEADM_TOKEN}
    unsafeSkipCAVerification: true
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd